### ISSUE TITLE
Doctrine import

### ISSUE THREAD

**Issue by yozmag** [josemalonsom/ifx4dd#1]
Im using symfony and doctrine, while using app/console "--ansi" "doctrine:mapping:import" "AppBundle" "yml" i got the following error:
[Doctrine\DBAL\DBALException]
  Unknown database type indexkeyarray requested, Doctrine\DBAL\Platforms\InformixPlatform may not support it.
Any ideia what it may be?
Thank you.

**Comment by yozmag** [comment]
I have mapped unknown data type to string to test import, but found a new error, that I can't pass.
  [Doctrine\ORM\Mapping\MappingException]
  Table systables has no primary key. Doctrine does not support reverse engineering from tables that don't have a primary key.
Found a online doc in http://www.ibm.com/developerworks/data/zones/informix/library/techarticle/0305parker/0305parker.html "this is syscolumns; it is joined to systables by a foreign key known as tabid (the primary key for systables)" so tabid is primary key. There shouldn't be an error.
Can you help me. Tks.

**Comment by josemalonsom** [comment]
Hi @yozmag

it seems that you are making the connection with the informix user. The InformixSchemaManager filters the tables by owner, so if you use the informix user all system tables will be listed what probably is not what you want. If you need to use the informix user in this case you can filter the tables with the --filter option:

`php app/console "--ansi" "doctrine:mapping:import" "AppBundle" "yml" --filter=MyFirstTable --filter=MySecondTable`

let me know if it solves your problem.

**Comment by yozmag** [comment]
Hi @josemalonsom , thank you for your answer,
the --filter just filters the output files, the error happens before the output on get metadata.
I add a where clause on listTablesSql, WHERE tabtype = \'T\' and tabid > 99 this leaves system tables out.
Thank you. please check my change request, if it makes sense to you.

**Comment by josemalonsom** [comment]
@yozmag you are right the --filter option does not avoid the error.

It can be done with the option `schema_filter` in your app/config/config.yml (http://symfony.com/doc/current/reference/configuration/doctrine.html), for example using: `schema_filter: /^(?!sys)/`, but ... i have tried it and there was an error in the InformixSchemaManager and the filter was not applied. I pushed a fix for it and now it works, you can prove it if you want.

I will take a look to your pull request.
